# https://cloud.google.com/blog/products/devops-sre/software-delivery-pipelines-with-gitlab-cicd-and-cloud-deploy/
stages:
  - typecheck
  - test
  - build
  - push
  - deploy

variables:
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  PROJECT: mimetic-retina-450410-q0 #civil-charmer-313017
  LOCATION: europe-west1
  SERVICE: tournament-api-app-dev
  AR_IMAGE: $LOCATION-docker.pkg.dev/$PROJECT/tournament-api/$SERVICE

.node-base: &node-base
  image: node:22
  before_script:
    - corepack enable && corepack prepare yarn@1.22.22 --activate
    - yarn install --frozen-lockfile

.ci-test-rules: &ci-test-rules
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "development"

typecheck:
  <<: [*node-base, *ci-test-rules]
  stage: typecheck
  script:
    - yarn typecheck

unit-test:
  <<: [*node-base, *ci-test-rules]
  stage: test
  script:
    - yarn test

build-job:
  stage: build
  services:
    - docker:24.0.5-dind
  image: docker:git
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
  before_script:
    - cp ${DEVELOPMENT_ENV_FILE} .env
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG --build-arg="COMMIT_SHA=$CI_COMMIT_SHORT_SHA" .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG

include:
  - component: gitlab.com/google-gitlab-components/artifact-registry/upload-artifact-registry@0.1.0
    inputs:
      stage: push
      source: $CI_REGISTRY_IMAGE:$IMAGE_TAG
      target: $AR_IMAGE:$IMAGE_TAG

  - component: gitlab.com/google-gitlab-components/cloud-run/deploy-cloud-run@0.1.0
    inputs:
      stage: deploy
      image: $AR_IMAGE:$IMAGE_TAG
      project_id: $PROJECT
      region: $LOCATION
      service: $SERVICE
